#' Make JAMES POST request
#'
#' @param host String with the host. The default is `"http://localhost:8080"`.
#' @param path String with the path to the called end point,
#' e.g. `"version"`, `"data/upload"` or `"data/upload/json"`.
#' @param query A list with query arguments, for example, `list(auto_unbox = TRUE)` for
#' `json` output, or `list(width = 7.09, height = 7.09)` for `svglite`.
#' @param txt Data set. Could be a URL, local file, JSON string or JSON object.
#' @param \dots Any other arguments passed to james functions via POST body
#' @return Object of class `c("james_httr", "response")`. The object extends
#' the [httr::response] object with the components:
#' `messages` (messages generated by JAMES), `warnings` (warnings generated
#' by JAMES), `parsed` (parsed return value of the called end point), `session`
#' (the session key).
#' @examples
#' \dontrun{
#' host <- "https://james.groeidiagrammen.nl"
#' # host <- "http://localhost:8080"
#' url <- paste0(
#'   "https://raw.githubusercontent.com/growthcharts/jamesdemodata/",
#'   "refs/heads/master/inst/json/examples/Laura_S.json")
#' fn <- system.file("extdata", "bds_v3.0", "smocc", "Laura_S.json",
#'  package = "jamesdemodata", mustWork = TRUE)
#' js <- read_json_js(txt = fn)
#' jo <- read_json_jo(txt = fn)
#'
#' #' try all inputs
#' m1 <- james_post(host = host, path = "data/upload/json", txt = fn)
#' m2 <- james_post(host = host, path = "data/upload/json", txt = js)
#' m3 <- james_post(host = host, path = "data/upload/json", txt = url)
#' m4 <- james_post(host = host, path = "data/upload/json", txt = jo)
#' }
#' \dontrun{
#' # create, store and view an A4 SVG plot
#' r5 <- james_post(path = "/charts/draw/svglite", txt = url,
#' chartcode = "NMBA", selector = "chartcode",
#' query = list(height = 29.7/2.54, width = 21/2.54))
#' tmp <- tempfile(pattern = "chart", fileext = ".svg")
#' writeLines(r5$parsed, con = tmp)
#' browseURL(tmp)
#' unlink(tmp)
#' }
#' @export
james_post <- function(
  host = "http://localhost:8080",
  path = character(0),
  query = list(),
  txt = NULL,
  ...
) {
  stopifnot(length(path) == 1L)
  stopifnot(length(txt) <= 1L)

  ua <- httr::user_agent(
    "https://github.com/growthcharts/jamesclient/blob/master/R/james_post.R"
  )

  # Safely build POST URL
  url <- httr::modify_url(host, path = path, query = query)

  # Read JSON
  txt <- read_json_js(txt = txt)

  if (is.null(txt) || validate(txt)) {
    resp <- httr::POST(
      url,
      ua,
      body = list(txt = txt, ...),
      encode = "json",
      httr::config()
    )
  } else {
    stop("Cannot process 'txt' argument: Invalid JSON.")
  }

  # Parse content
  parsed <- NULL
  if (httr::http_error(resp)) {
    msg <- httr::content(resp, type = "text/plain", encoding = "UTF-8")
    parsed <- sprintf(
      "JAMES API request failed [%s]\n%s\n<%s>",
      httr::status_code(resp),
      msg,
      url
    )
  } else {
    type <- httr::http_type(resp)
    if (type %in% c("application/json", "text/plain", "image/svg+xml")) {
      parsed <- httr::content(resp, "text", encoding = "UTF-8")
      if (type == "application/json") {
        parsed <- jsonlite::fromJSON(parsed)
      }
    } else {
      parsed <- httr::content(resp, as = "parsed")
    }
  }

  # Extract session ID
  session_id <- get_url(resp, "session")

  # Build URLs for warnings and messages
  warnings <- ""
  messages <- ""

  if (!is.null(session_id) && nzchar(session_id)) {
    urlw <- httr::modify_url(host, path = paste0(session_id, "/warnings/text"))
    urlm <- httr::modify_url(host, path = paste0(session_id, "/messages/text"))

    warnings <- tryCatch(
      httr::content(
        httr::GET(urlw, config = httr::config()),
        "text",
        type = "text/plain",
        encoding = "UTF-8"
      ),
      error = function(e) ""
    )
    messages <- tryCatch(
      httr::content(
        httr::GET(urlm, config = httr::config()),
        "text",
        type = "text/plain",
        encoding = "UTF-8"
      ),
      error = function(e) ""
    )
  }

  # Extend response
  resp$request_path <- path
  resp$parsed <- parsed
  resp$warnings <- warnings
  resp$messages <- messages
  resp$session <- session_id

  class(resp) <- c("james_httr", "response")
  return(resp)
}

#' @export
print.james_httr <- function(x, ...) {
  cat("JAMES request:\n")
  cat("  Path    : ", x$request_path, "\n", sep = "")
  cat("  Status  : ", httr::status_code(x), "\n", sep = "")
  cat("  Session : ", x$session %||% "None", "\n", sep = "")

  # Print messages if available
  if (nzchar(x$messages)) {
    cat("\nMessages:\n")
    cat(x$messages, "\n")
  }

  # Print warnings if available
  if (nzchar(x$warnings)) {
    cat("\nWarnings:\n")
    cat(x$warnings, "\n")
  }

  # Print parsed content
  cat("\nParsed response:\n")

  if (is.character(x$parsed) && nchar(x$parsed) > 1000) {
    cat(substr(x$parsed, 1, 1000), "...\n[truncated]\n")
  } else if (is.atomic(x$parsed) || is.null(x$parsed)) {
    print(x$parsed)
  } else {
    str(x$parsed, ...)
  }

  invisible(x)
}
