#' Make JAMES POST request
#'
#' @param host String with the host. The default is `"http://localhost"`.
#' @param path String with the path to the called end point,
#' e.g. `"version"`, `"data/upload"` or `"data/upload/json"`.
#' @param query A list with query arguments, for example, `list(auto_unbox = TRUE)` for
#' `json` output, or `list(width = 7.09, height = 7.09)` for `svglite`.
#' @param txt Data set. Could be a URL, local file, JSON string or JSON object.
#' @param auth Bearer token for authentication.
#' @param \dots Any other arguments passed to james functions via POST body
#' @return Object of class `c("james_httr", "response")`. The object extends
#' the [httr::response] object with the components:
#' `messages` (messages generated by JAMES), `warnings` (warnings generated
#' by JAMES), `parsed` (parsed return value of the called end point), `session`
#' (the session key).
#' @examples
#' \dontrun{
#' url <- "http://localhost/ocpu/library/bdsreader/examples/Laura_S.json"
#' fn <- system.file("extdata", "bds_v3.0", "smocc", "Laura_S.json",
#'  package = "jamesdemodata", mustWork = TRUE)
#' js <- read_json_js(txt = fn)
#' jo <- read_json_jo(txt = fn)
#'
#' #' try all inputs
#' m1 <- james_post(path = "data/upload/json", txt = fn)
#' m2 <- james_post(path = "data/upload/json", txt = js)
#' m3 <- james_post(path = "data/upload/json", txt = url)
#' m4 <- james_post(path = "data/upload/json", txt = jo)
#' }
#' \dontrun{
#' # create, store and view an A4 SVG plot
#' r5 <- james_post(path = "/charts/draw/svglite", txt = url,
#' chartcode = "NMBA", selector = "chartcode",
#' query = list(height = 29.7/2.54, width = 21/2.54))
#' tmp <- tempfile(pattern = "chart", fileext = ".svg")
#' writeLines(r5$parsed, con = tmp)
#' browseURL(tmp)
#' unlink(tmp)
#' }
#' @export
james_post <- function(host = "http://localhost",
                       path = character(0),
                       query = list(),
                       txt = NULL,
                       auth = NULL,
                       ...) {
  stopifnot(length(path) == 1L)
  stopifnot(length(txt) <= 1L)
  ua <- user_agent("https://github.com/growthcharts/jamesclient/blob/master/R/james_post.R")
  url <- parse_url(host)
  url <- modify_url(url = url, path = file.path(url$path, path), query = query)
  if (!is.null(auth)) {
    headers <- add_headers("Authorization" = paste("Bearer", auth))
  } else headers <- add_headers("")

  # if we have a file name or URL, read into string
  txt <- read_json_js(txt = txt)

  # check JSON
  if (is.null(txt) || validate(txt)) {
    resp <- POST(url, ua,
                 headers,
                 body = list(txt = txt,
                             ...),
                 encode = "json")
  } else {
    stop("Cannot process 'txt' argument.")
  }

  # parse contents
  parsed <- ""
  if (http_error(resp)) {
    msg <- content(resp, type = "text/plain", encoding = "UTF-8")
    parsed <- sprintf(
      "JAMES API request failed [%s]\n%s\n<%s>",
      status_code(resp), msg, url)
  } else {

    if (http_type(resp) == "application/json") {
      parsed <- jsonlite::fromJSON(content(resp, "text", encoding = "UTF-8"))
    }

    if (http_type(resp) == "text/plain") {
      parsed <- content(resp, "text", encoding = "UTF-8")
    }

    if (http_type(resp) == "image/svg+xml") {
      parsed <- content(resp, "text", encoding = "UTF-8")
    }

    if (is.null(parsed)) {
      parsed <- content(resp, as = "parsed")
    }
  }

  # extract warnings
  urlw <- file.path(host, get_url(resp, "session"), "warnings/text")
  if (length(urlw)) {
    warnings <- content(GET(urlw), "text", type = "text/plain", encoding = "UTF-8")
  } else {
    warnings <- ""
  }

  # extract messages
  urlm <- file.path(host, get_url(resp, "session"), "messages/text")
  if (length(urlm)) {
    messages <- content(GET(urlm), "text", type = "text/plain", encoding = "UTF-8")
  } else {
    messages <- ""
  }

  # extend standard httr response
  resp$request_path <- path
  resp$parsed <- parsed
  resp$warnings <- warnings
  resp$messages <- messages
  resp$session <- get_url(resp, "session")

  class(resp) <- c("james_httr", "response")
  return(resp)
}

#' @export
print.james_httr <- function(x, ...) {
  cat("JAMES request: ", x$request_path, "\n", sep = "")
  if (nchar(x$messages)) str(x$messages)
  if (nchar(x$warnings)) str(x$warnings)
  str(x$parsed)
  invisible(x)
}
